### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "fulano@test.com",
  "name": "fulano",
  "password": "dq3dq3dq3eq3e"
}

### Get users list
GET http://localhost:3000/users

### Get a user
GET http://localhost:3000/users/9

### Replace a user
PUT http://localhost:3000/users/9
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "test",
  "password": "Description 1",
  "birthAt": "1995-10-10"
}

### Update a user
PATCH http://localhost:3000/users/9
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "test",
  "birthAt": "1995-10-10"
}

### Delete a user
DELETE  http://localhost:3000/users/7