@baseurl = http://localhost:3000

### Create user
POST {{baseurl}}/users
Content-Type: application/json

{
  "email": "matheus@test.com",
  "name": "Matheus",
  "password": "1234567"
}

### Get users list
GET {{baseurl}}/users

### Get a user
GET {{baseurl}}/users/9

### Replace a user
PUT {{baseurl}}/users/9
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "test",
  "password": "Description 1",
  "birthAt": "1995-10-10"
}

### Update a user
PATCH {{baseurl}}/users/12
Content-Type: application/json

{
  "password": "123456789"
}

### Delete a user
DELETE  {{baseurl}}/users/7


# Auth Module

### Login
POST {{baseurl}}/auth/login
Content-Type: application/json

{
  "email": "matheus@test.com",
  "password": "123456789"
}


### Me

POST {{baseurl}}/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJNYXRoZXVzIiwiZW1haWwiOiJtYXRoZXVzQHRlc3QuY29tIiwiaWF0IjoxNzAyOTQ3Njc0LCJleHAiOjE3MDM1NTI0NzQsImF1ZCI6InVzZXJzIiwiaXNzIjoibG9naW4iLCJzdWIiOiIxMiJ9.7bq7JATMYT48NzEQ1neduaQHGihNQpj140zee-rB5S8
