version: '3'
services:
  app:
    build: .
    # command: "./.docker/start.sh"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    restart: always
  mysql:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nest-prisma
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
    restart: always
