version: '3'
services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nest-prisma
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    restart: always
  test-mysql:
    image: mysql:8.0.30-debian
    ports:
      - 3300:3306
    environment:
      - MYSQL_DATABASE=nest-prisma
      - MYSQL_ROOT_PASSWORD=root
    security_opt:
      - seccomp:unconfined
    restart: always
